name: "Artifactory Publish"
description: "GitHub Action that publishes packages to JFrog Artifactory"

inputs:
  repository-type:  
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Publish NPM Package
      if: ${{ inputs.repository-type == 'npm' }}
      uses: ./npm