name: Publish artifact
run-name: Publishing ${{ inputs.repository-type }} ${{ github.workflow }} triggered by @${{ github.triggering_actor }}

on: 
  workflow_call:   
    inputs:
      repository-type:
        default: ""
        description: "The type of package to publish"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jfrog/setup-jfrog-cli@v3.4.0
        env:
          JF_ENV_MONDO192: ${{ secrets.JF_SECRET_ENV_MONDO192 }}
        with:
          version: "2.45.0"
      
      - if: ${{ inputs.repository-type == 'npm' }}
        uses: ./npm
    