name: Publish artifact
author: Me
description: Publish artifacts to Artifactory on JFrog Platform

inputs:
  artifact-type:
    description: The type of artifact being published
    required: true
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - if: ${{ inputs.artifact-type == "npm" }}
      uses: ./npm 