name: Test

on: 
    pull_request: 
        types: [closed, opened, synchronize]
    
    workflow_dispatch: 

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Run action
              uses: ./
              with:
                artifact-type: "npm"
